// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppUsersColumns holds the columns for the "app_users" table.
	AppUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Size: 255},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 255},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "is_active", Type: field.TypeBool, Default: false},
	}
	// AppUsersTable holds the schema information for the "app_users" table.
	AppUsersTable = &schema.Table{
		Name:       "app_users",
		Columns:    AppUsersColumns,
		PrimaryKey: []*schema.Column{AppUsersColumns[0]},
	}
	// SharesColumns holds the columns for the "shares" table.
	SharesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expiration", Type: field.TypeTime},
		{Name: "share_code", Type: field.TypeString, Unique: true},
		{Name: "data", Type: field.TypeJSON},
		{Name: "creator_id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeString, Default: "created"},
	}
	// SharesTable holds the schema information for the "shares" table.
	SharesTable = &schema.Table{
		Name:       "shares",
		Columns:    SharesColumns,
		PrimaryKey: []*schema.Column{SharesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppUsersTable,
		SharesTable,
	}
)

func init() {
}
