// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basket-buddy-backend/ent/appuser"
	"basket-buddy-backend/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AppUserQuery is the builder for querying AppUser entities.
type AppUserQuery struct {
	config
	ctx        *QueryContext
	order      []appuser.OrderOption
	inters     []Interceptor
	predicates []predicate.AppUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppUserQuery builder.
func (auq *AppUserQuery) Where(ps ...predicate.AppUser) *AppUserQuery {
	auq.predicates = append(auq.predicates, ps...)
	return auq
}

// Limit the number of records to be returned by this query.
func (auq *AppUserQuery) Limit(limit int) *AppUserQuery {
	auq.ctx.Limit = &limit
	return auq
}

// Offset to start from.
func (auq *AppUserQuery) Offset(offset int) *AppUserQuery {
	auq.ctx.Offset = &offset
	return auq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (auq *AppUserQuery) Unique(unique bool) *AppUserQuery {
	auq.ctx.Unique = &unique
	return auq
}

// Order specifies how the records should be ordered.
func (auq *AppUserQuery) Order(o ...appuser.OrderOption) *AppUserQuery {
	auq.order = append(auq.order, o...)
	return auq
}

// First returns the first AppUser entity from the query.
// Returns a *NotFoundError when no AppUser was found.
func (auq *AppUserQuery) First(ctx context.Context) (*AppUser, error) {
	nodes, err := auq.Limit(1).All(setContextOp(ctx, auq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (auq *AppUserQuery) FirstX(ctx context.Context) *AppUser {
	node, err := auq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppUser ID from the query.
// Returns a *NotFoundError when no AppUser ID was found.
func (auq *AppUserQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = auq.Limit(1).IDs(setContextOp(ctx, auq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (auq *AppUserQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := auq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppUser entity is found.
// Returns a *NotFoundError when no AppUser entities are found.
func (auq *AppUserQuery) Only(ctx context.Context) (*AppUser, error) {
	nodes, err := auq.Limit(2).All(setContextOp(ctx, auq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appuser.Label}
	default:
		return nil, &NotSingularError{appuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (auq *AppUserQuery) OnlyX(ctx context.Context) *AppUser {
	node, err := auq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppUser ID in the query.
// Returns a *NotSingularError when more than one AppUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (auq *AppUserQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = auq.Limit(2).IDs(setContextOp(ctx, auq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appuser.Label}
	default:
		err = &NotSingularError{appuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (auq *AppUserQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := auq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppUsers.
func (auq *AppUserQuery) All(ctx context.Context) ([]*AppUser, error) {
	ctx = setContextOp(ctx, auq.ctx, "All")
	if err := auq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AppUser, *AppUserQuery]()
	return withInterceptors[[]*AppUser](ctx, auq, qr, auq.inters)
}

// AllX is like All, but panics if an error occurs.
func (auq *AppUserQuery) AllX(ctx context.Context) []*AppUser {
	nodes, err := auq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppUser IDs.
func (auq *AppUserQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if auq.ctx.Unique == nil && auq.path != nil {
		auq.Unique(true)
	}
	ctx = setContextOp(ctx, auq.ctx, "IDs")
	if err = auq.Select(appuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (auq *AppUserQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := auq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (auq *AppUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, auq.ctx, "Count")
	if err := auq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, auq, querierCount[*AppUserQuery](), auq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (auq *AppUserQuery) CountX(ctx context.Context) int {
	count, err := auq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (auq *AppUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, auq.ctx, "Exist")
	switch _, err := auq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (auq *AppUserQuery) ExistX(ctx context.Context) bool {
	exist, err := auq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (auq *AppUserQuery) Clone() *AppUserQuery {
	if auq == nil {
		return nil
	}
	return &AppUserQuery{
		config:     auq.config,
		ctx:        auq.ctx.Clone(),
		order:      append([]appuser.OrderOption{}, auq.order...),
		inters:     append([]Interceptor{}, auq.inters...),
		predicates: append([]predicate.AppUser{}, auq.predicates...),
		// clone intermediate query.
		sql:  auq.sql.Clone(),
		path: auq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppUser.Query().
//		GroupBy(appuser.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (auq *AppUserQuery) GroupBy(field string, fields ...string) *AppUserGroupBy {
	auq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AppUserGroupBy{build: auq}
	grbuild.flds = &auq.ctx.Fields
	grbuild.label = appuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.AppUser.Query().
//		Select(appuser.FieldUsername).
//		Scan(ctx, &v)
func (auq *AppUserQuery) Select(fields ...string) *AppUserSelect {
	auq.ctx.Fields = append(auq.ctx.Fields, fields...)
	sbuild := &AppUserSelect{AppUserQuery: auq}
	sbuild.label = appuser.Label
	sbuild.flds, sbuild.scan = &auq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AppUserSelect configured with the given aggregations.
func (auq *AppUserQuery) Aggregate(fns ...AggregateFunc) *AppUserSelect {
	return auq.Select().Aggregate(fns...)
}

func (auq *AppUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range auq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, auq); err != nil {
				return err
			}
		}
	}
	for _, f := range auq.ctx.Fields {
		if !appuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if auq.path != nil {
		prev, err := auq.path(ctx)
		if err != nil {
			return err
		}
		auq.sql = prev
	}
	return nil
}

func (auq *AppUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AppUser, error) {
	var (
		nodes = []*AppUser{}
		_spec = auq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AppUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AppUser{config: auq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, auq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (auq *AppUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := auq.querySpec()
	_spec.Node.Columns = auq.ctx.Fields
	if len(auq.ctx.Fields) > 0 {
		_spec.Unique = auq.ctx.Unique != nil && *auq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, auq.driver, _spec)
}

func (auq *AppUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(appuser.Table, appuser.Columns, sqlgraph.NewFieldSpec(appuser.FieldID, field.TypeUUID))
	_spec.From = auq.sql
	if unique := auq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if auq.path != nil {
		_spec.Unique = true
	}
	if fields := auq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appuser.FieldID)
		for i := range fields {
			if fields[i] != appuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := auq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := auq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := auq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := auq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (auq *AppUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(auq.driver.Dialect())
	t1 := builder.Table(appuser.Table)
	columns := auq.ctx.Fields
	if len(columns) == 0 {
		columns = appuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if auq.sql != nil {
		selector = auq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if auq.ctx.Unique != nil && *auq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range auq.predicates {
		p(selector)
	}
	for _, p := range auq.order {
		p(selector)
	}
	if offset := auq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := auq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AppUserGroupBy is the group-by builder for AppUser entities.
type AppUserGroupBy struct {
	selector
	build *AppUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (augb *AppUserGroupBy) Aggregate(fns ...AggregateFunc) *AppUserGroupBy {
	augb.fns = append(augb.fns, fns...)
	return augb
}

// Scan applies the selector query and scans the result into the given value.
func (augb *AppUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, augb.build.ctx, "GroupBy")
	if err := augb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AppUserQuery, *AppUserGroupBy](ctx, augb.build, augb, augb.build.inters, v)
}

func (augb *AppUserGroupBy) sqlScan(ctx context.Context, root *AppUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(augb.fns))
	for _, fn := range augb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*augb.flds)+len(augb.fns))
		for _, f := range *augb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*augb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := augb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AppUserSelect is the builder for selecting fields of AppUser entities.
type AppUserSelect struct {
	*AppUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aus *AppUserSelect) Aggregate(fns ...AggregateFunc) *AppUserSelect {
	aus.fns = append(aus.fns, fns...)
	return aus
}

// Scan applies the selector query and scans the result into the given value.
func (aus *AppUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aus.ctx, "Select")
	if err := aus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AppUserQuery, *AppUserSelect](ctx, aus.AppUserQuery, aus, aus.inters, v)
}

func (aus *AppUserSelect) sqlScan(ctx context.Context, root *AppUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aus.fns))
	for _, fn := range aus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
