// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basket-buddy-backend/ent/appuser"
	"basket-buddy-backend/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AppUserDelete is the builder for deleting a AppUser entity.
type AppUserDelete struct {
	config
	hooks    []Hook
	mutation *AppUserMutation
}

// Where appends a list predicates to the AppUserDelete builder.
func (aud *AppUserDelete) Where(ps ...predicate.AppUser) *AppUserDelete {
	aud.mutation.Where(ps...)
	return aud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aud *AppUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, aud.sqlExec, aud.mutation, aud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (aud *AppUserDelete) ExecX(ctx context.Context) int {
	n, err := aud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aud *AppUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(appuser.Table, sqlgraph.NewFieldSpec(appuser.FieldID, field.TypeUUID))
	if ps := aud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, aud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	aud.mutation.done = true
	return affected, err
}

// AppUserDeleteOne is the builder for deleting a single AppUser entity.
type AppUserDeleteOne struct {
	aud *AppUserDelete
}

// Where appends a list predicates to the AppUserDelete builder.
func (audo *AppUserDeleteOne) Where(ps ...predicate.AppUser) *AppUserDeleteOne {
	audo.aud.mutation.Where(ps...)
	return audo
}

// Exec executes the deletion query.
func (audo *AppUserDeleteOne) Exec(ctx context.Context) error {
	n, err := audo.aud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{appuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (audo *AppUserDeleteOne) ExecX(ctx context.Context) {
	if err := audo.Exec(ctx); err != nil {
		panic(err)
	}
}
