// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basket-buddy-backend/ent/appuser"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AppUserCreate is the builder for creating a AppUser entity.
type AppUserCreate struct {
	config
	mutation *AppUserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (auc *AppUserCreate) SetUsername(s string) *AppUserCreate {
	auc.mutation.SetUsername(s)
	return auc
}

// SetEmail sets the "email" field.
func (auc *AppUserCreate) SetEmail(s string) *AppUserCreate {
	auc.mutation.SetEmail(s)
	return auc
}

// SetRole sets the "role" field.
func (auc *AppUserCreate) SetRole(s string) *AppUserCreate {
	auc.mutation.SetRole(s)
	return auc
}

// SetCreatedAt sets the "created_at" field.
func (auc *AppUserCreate) SetCreatedAt(t time.Time) *AppUserCreate {
	auc.mutation.SetCreatedAt(t)
	return auc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (auc *AppUserCreate) SetNillableCreatedAt(t *time.Time) *AppUserCreate {
	if t != nil {
		auc.SetCreatedAt(*t)
	}
	return auc
}

// SetIsActive sets the "is_active" field.
func (auc *AppUserCreate) SetIsActive(b bool) *AppUserCreate {
	auc.mutation.SetIsActive(b)
	return auc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (auc *AppUserCreate) SetNillableIsActive(b *bool) *AppUserCreate {
	if b != nil {
		auc.SetIsActive(*b)
	}
	return auc
}

// SetID sets the "id" field.
func (auc *AppUserCreate) SetID(u uuid.UUID) *AppUserCreate {
	auc.mutation.SetID(u)
	return auc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (auc *AppUserCreate) SetNillableID(u *uuid.UUID) *AppUserCreate {
	if u != nil {
		auc.SetID(*u)
	}
	return auc
}

// Mutation returns the AppUserMutation object of the builder.
func (auc *AppUserCreate) Mutation() *AppUserMutation {
	return auc.mutation
}

// Save creates the AppUser in the database.
func (auc *AppUserCreate) Save(ctx context.Context) (*AppUser, error) {
	auc.defaults()
	return withHooks(ctx, auc.sqlSave, auc.mutation, auc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (auc *AppUserCreate) SaveX(ctx context.Context) *AppUser {
	v, err := auc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (auc *AppUserCreate) Exec(ctx context.Context) error {
	_, err := auc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auc *AppUserCreate) ExecX(ctx context.Context) {
	if err := auc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auc *AppUserCreate) defaults() {
	if _, ok := auc.mutation.CreatedAt(); !ok {
		v := appuser.DefaultCreatedAt()
		auc.mutation.SetCreatedAt(v)
	}
	if _, ok := auc.mutation.IsActive(); !ok {
		v := appuser.DefaultIsActive
		auc.mutation.SetIsActive(v)
	}
	if _, ok := auc.mutation.ID(); !ok {
		v := appuser.DefaultID()
		auc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auc *AppUserCreate) check() error {
	if _, ok := auc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AppUser.username"`)}
	}
	if v, ok := auc.mutation.Username(); ok {
		if err := appuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AppUser.username": %w`, err)}
		}
	}
	if _, ok := auc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "AppUser.email"`)}
	}
	if v, ok := auc.mutation.Email(); ok {
		if err := appuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "AppUser.email": %w`, err)}
		}
	}
	if _, ok := auc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "AppUser.role"`)}
	}
	if v, ok := auc.mutation.Role(); ok {
		if err := appuser.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AppUser.role": %w`, err)}
		}
	}
	if _, ok := auc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppUser.created_at"`)}
	}
	if _, ok := auc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "AppUser.is_active"`)}
	}
	return nil
}

func (auc *AppUserCreate) sqlSave(ctx context.Context) (*AppUser, error) {
	if err := auc.check(); err != nil {
		return nil, err
	}
	_node, _spec := auc.createSpec()
	if err := sqlgraph.CreateNode(ctx, auc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	auc.mutation.id = &_node.ID
	auc.mutation.done = true
	return _node, nil
}

func (auc *AppUserCreate) createSpec() (*AppUser, *sqlgraph.CreateSpec) {
	var (
		_node = &AppUser{config: auc.config}
		_spec = sqlgraph.NewCreateSpec(appuser.Table, sqlgraph.NewFieldSpec(appuser.FieldID, field.TypeUUID))
	)
	if id, ok := auc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := auc.mutation.Username(); ok {
		_spec.SetField(appuser.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := auc.mutation.Email(); ok {
		_spec.SetField(appuser.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := auc.mutation.Role(); ok {
		_spec.SetField(appuser.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := auc.mutation.CreatedAt(); ok {
		_spec.SetField(appuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := auc.mutation.IsActive(); ok {
		_spec.SetField(appuser.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	return _node, _spec
}

// AppUserCreateBulk is the builder for creating many AppUser entities in bulk.
type AppUserCreateBulk struct {
	config
	err      error
	builders []*AppUserCreate
}

// Save creates the AppUser entities in the database.
func (aucb *AppUserCreateBulk) Save(ctx context.Context) ([]*AppUser, error) {
	if aucb.err != nil {
		return nil, aucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(aucb.builders))
	nodes := make([]*AppUser, len(aucb.builders))
	mutators := make([]Mutator, len(aucb.builders))
	for i := range aucb.builders {
		func(i int, root context.Context) {
			builder := aucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aucb *AppUserCreateBulk) SaveX(ctx context.Context) []*AppUser {
	v, err := aucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aucb *AppUserCreateBulk) Exec(ctx context.Context) error {
	_, err := aucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aucb *AppUserCreateBulk) ExecX(ctx context.Context) {
	if err := aucb.Exec(ctx); err != nil {
		panic(err)
	}
}
