// Code generated by ent, DO NOT EDIT.

package ent

import (
	"basket-buddy-backend/ent/predicate"
	"basket-buddy-backend/ent/share"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ShareUpdate is the builder for updating Share entities.
type ShareUpdate struct {
	config
	hooks    []Hook
	mutation *ShareMutation
}

// Where appends a list predicates to the ShareUpdate builder.
func (su *ShareUpdate) Where(ps ...predicate.Share) *ShareUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *ShareUpdate) SetCreatedAt(t time.Time) *ShareUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *ShareUpdate) SetNillableCreatedAt(t *time.Time) *ShareUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// SetExpiration sets the "expiration" field.
func (su *ShareUpdate) SetExpiration(t time.Time) *ShareUpdate {
	su.mutation.SetExpiration(t)
	return su
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (su *ShareUpdate) SetNillableExpiration(t *time.Time) *ShareUpdate {
	if t != nil {
		su.SetExpiration(*t)
	}
	return su
}

// SetShareCode sets the "share_code" field.
func (su *ShareUpdate) SetShareCode(s string) *ShareUpdate {
	su.mutation.SetShareCode(s)
	return su
}

// SetNillableShareCode sets the "share_code" field if the given value is not nil.
func (su *ShareUpdate) SetNillableShareCode(s *string) *ShareUpdate {
	if s != nil {
		su.SetShareCode(*s)
	}
	return su
}

// SetData sets the "data" field.
func (su *ShareUpdate) SetData(m map[string]interface{}) *ShareUpdate {
	su.mutation.SetData(m)
	return su
}

// SetCreatorID sets the "creator_id" field.
func (su *ShareUpdate) SetCreatorID(u uuid.UUID) *ShareUpdate {
	su.mutation.SetCreatorID(u)
	return su
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (su *ShareUpdate) SetNillableCreatorID(u *uuid.UUID) *ShareUpdate {
	if u != nil {
		su.SetCreatorID(*u)
	}
	return su
}

// Mutation returns the ShareMutation object of the builder.
func (su *ShareUpdate) Mutation() *ShareMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ShareUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ShareUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ShareUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ShareUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *ShareUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.Expiration(); ok {
		_spec.SetField(share.FieldExpiration, field.TypeTime, value)
	}
	if value, ok := su.mutation.ShareCode(); ok {
		_spec.SetField(share.FieldShareCode, field.TypeString, value)
	}
	if value, ok := su.mutation.Data(); ok {
		_spec.SetField(share.FieldData, field.TypeJSON, value)
	}
	if value, ok := su.mutation.CreatorID(); ok {
		_spec.SetField(share.FieldCreatorID, field.TypeUUID, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ShareUpdateOne is the builder for updating a single Share entity.
type ShareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShareMutation
}

// SetCreatedAt sets the "created_at" field.
func (suo *ShareUpdateOne) SetCreatedAt(t time.Time) *ShareUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableCreatedAt(t *time.Time) *ShareUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// SetExpiration sets the "expiration" field.
func (suo *ShareUpdateOne) SetExpiration(t time.Time) *ShareUpdateOne {
	suo.mutation.SetExpiration(t)
	return suo
}

// SetNillableExpiration sets the "expiration" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableExpiration(t *time.Time) *ShareUpdateOne {
	if t != nil {
		suo.SetExpiration(*t)
	}
	return suo
}

// SetShareCode sets the "share_code" field.
func (suo *ShareUpdateOne) SetShareCode(s string) *ShareUpdateOne {
	suo.mutation.SetShareCode(s)
	return suo
}

// SetNillableShareCode sets the "share_code" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableShareCode(s *string) *ShareUpdateOne {
	if s != nil {
		suo.SetShareCode(*s)
	}
	return suo
}

// SetData sets the "data" field.
func (suo *ShareUpdateOne) SetData(m map[string]interface{}) *ShareUpdateOne {
	suo.mutation.SetData(m)
	return suo
}

// SetCreatorID sets the "creator_id" field.
func (suo *ShareUpdateOne) SetCreatorID(u uuid.UUID) *ShareUpdateOne {
	suo.mutation.SetCreatorID(u)
	return suo
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (suo *ShareUpdateOne) SetNillableCreatorID(u *uuid.UUID) *ShareUpdateOne {
	if u != nil {
		suo.SetCreatorID(*u)
	}
	return suo
}

// Mutation returns the ShareMutation object of the builder.
func (suo *ShareUpdateOne) Mutation() *ShareMutation {
	return suo.mutation
}

// Where appends a list predicates to the ShareUpdate builder.
func (suo *ShareUpdateOne) Where(ps ...predicate.Share) *ShareUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ShareUpdateOne) Select(field string, fields ...string) *ShareUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Share entity.
func (suo *ShareUpdateOne) Save(ctx context.Context) (*Share, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ShareUpdateOne) SaveX(ctx context.Context) *Share {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ShareUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ShareUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *ShareUpdateOne) sqlSave(ctx context.Context) (_node *Share, err error) {
	_spec := sqlgraph.NewUpdateSpec(share.Table, share.Columns, sqlgraph.NewFieldSpec(share.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Share.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, share.FieldID)
		for _, f := range fields {
			if !share.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != share.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(share.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.Expiration(); ok {
		_spec.SetField(share.FieldExpiration, field.TypeTime, value)
	}
	if value, ok := suo.mutation.ShareCode(); ok {
		_spec.SetField(share.FieldShareCode, field.TypeString, value)
	}
	if value, ok := suo.mutation.Data(); ok {
		_spec.SetField(share.FieldData, field.TypeJSON, value)
	}
	if value, ok := suo.mutation.CreatorID(); ok {
		_spec.SetField(share.FieldCreatorID, field.TypeUUID, value)
	}
	_node = &Share{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{share.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
