// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppUser is the predicate function for appuser builders.
type AppUser func(*sql.Selector)

// Share is the predicate function for share builders.
type Share func(*sql.Selector)
